

BoxLayout:
    DraggableBoxLayout:
        drag_classes: ['label']
        orientation: 'vertical'
        Label:
            text: 'A'
        Label:
            text: 'A'
        Label:
            text: 'A'
    DraggableBoxLayout:
        drag_classes: ['label']
        orientation: 'vertical'
        DragLabel:
            text: 'A*'
            drag_cls: 'label'
        DragLabel:
            text: 'A*'
            drag_cls: 'label'
